"""empty message

Revision ID: 685d396d8dca
Revises: 
Create Date: 2018-02-12 12:45:14.946220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '685d396d8dca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('vk_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=55), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vk_id')
    )
    op.create_table('wish',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('text', sa.Unicode(length=128), nullable=False),
    sa.Column('description', sa.Unicode(length=255), nullable=True),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('image', sa.Unicode(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wish')
    op.drop_table('user')
    # ### end Alembic commands ###
